// Generated by dojo-bindgen on Mon, 29 Apr 2024 18:54:59 +0000. Do not modify this file manually.
using UnityEngine;
using System;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;

// Model definition for `zklash::models::foe::Foe` model
public class Foe : ModelInstance 
{
    [ModelField("registry_id")]
    public uint registry_id;

    [ModelField("squad_id")]
    public uint squad_id;

    [ModelField("id")]
    public byte id;

    [ModelField("role")]
    public byte role;

    [ModelField("item")]
    public byte item;

    [ModelField("level")]
    public byte level;

    [ModelField("health")]
    public byte health;

    [ModelField("attack")]
    public byte attack;

    [ModelField("absorb")]
    public byte absorb;

    [ModelField("stun")]
    public byte stun;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }

    public override void OnUpdate(Model model)
    {
        //Debug.Log($"Player updated: {model}");
        base.OnUpdate(model);
    }
}
        