// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:03:07 +0000. Do not modify this file manually.
using UnityEngine;
using System;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;


// Model definition for `zklash::models::player::Player` model
public class Player : ModelInstance
{
    [ModelField("id")]
    public FieldElement id;

    [ModelField("name")]
    public FieldElement name;

    [ModelField("team_count")]
    public uint team_count;

    [ModelField("win_count")]
    public uint win_count;

    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update()
    {
    }

    public override void OnUpdate(Model model)
    {
        //Debug.Log($"Player updated: {model}");
        base.OnUpdate(model);
    }
}
