// Generated by dojo-bindgen on Mon, 29 Apr 2024 18:54:59 +0000. Do not modify this file manually.
using UnityEngine;
using System;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;

// Model definition for `zklash::models::registry::Registry` model
public class Registry : ModelInstance {
    [ModelField("id")]
    public uint id;

    [ModelField("squad_count")]
    public uint squad_count;

    [ModelField("leagues")]
    public FieldElement leagues;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }

    public override void OnUpdate(Model model)
    {
        //Debug.Log($"Player updated: {model}");
        base.OnUpdate(model);
    }
}
        