// Generated by dojo-bindgen on Mon, 29 Apr 2024 18:54:59 +0000. Do not modify this file manually.
using UnityEngine;
using System;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;

// Model definition for `zklash::models::squad::Squad` model
public class Squad : ModelInstance {
    [ModelField("registry_id")]
    public uint registry_id;

    [ModelField("id")]
    public uint id;

    [ModelField("league_id")]
    public byte league_id;

    [ModelField("index")]
    public uint index;

    [ModelField("rating")]
    public uint rating;

    [ModelField("size")]
    public byte size;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }

    public override void OnUpdate(Model model)
    {
        //Debug.Log($"Player updated: {model}");
        base.OnUpdate(model);
    }
}
        