// Generated by dojo-bindgen on Wed, 14 Aug 2024 21:35:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace zklash {
    // Model definition for `zklash::models::index::Foe` model
    public class Foe : ModelInstance {
        [ModelField("registry_id")]
        public uint registry_id;

        [ModelField("squad_id")]
        public uint squad_id;

        [ModelField("id")]
        public byte id;

        [ModelField("role")]
        public byte role;

        [ModelField("item")]
        public byte item;

        [ModelField("level")]
        public byte level;

        [ModelField("health")]
        public byte health;

        [ModelField("attack")]
        public byte attack;

        [ModelField("absorb")]
        public byte absorb;

        [ModelField("stun")]
        public byte stun;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        