// Generated by dojo-bindgen on Wed, 14 Aug 2024 21:35:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace zklash {
    // Model definition for `zklash::models::index::Shop` model
    public class Shop : ModelInstance {
        [ModelField("player_id")]
        public FieldElement player_id;

        [ModelField("team_id")]
        public uint team_id;

        [ModelField("reroll_cost")]
        public byte reroll_cost;

        [ModelField("item_count")]
        public byte item_count;

        [ModelField("items")]
        public uint items;

        [ModelField("role_count")]
        public byte role_count;

        [ModelField("roles")]
        public uint roles;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        