// Generated by dojo-bindgen on Wed, 14 Aug 2024 21:35:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo::model::layout::FieldLayout` struct
[Serializable]
public struct FieldLayout {
    public FieldElement selector;
    public Layout layout;
}

// Type definition for `core::byte_array::ByteArray` struct
[Serializable]
public struct ByteArray {
    public string[] data;
    public FieldElement pending_word;
    public uint pending_word_len;
}

// Type definition for `dojo::model::layout::Layout` enum
public abstract record Layout() : Enum {
    public record Fixed(byte[] value) : Layout;
    public record Struct(FieldLayout[] value) : Layout;
    public record Tuple(Layout[] value) : Layout;
    public record Array(Layout[] value) : Layout;
    public record ByteArray() : Layout;
    public record Enum(FieldLayout[] value) : Layout;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


namespace zklash {
    // Model definition for `zklash::models::index::Character` model
    public class Character : ModelInstance {
        [ModelField("player_id")]
        public FieldElement player_id;

        [ModelField("team_id")]
        public uint team_id;

        [ModelField("id")]
        public byte id;

        [ModelField("role")]
        public byte role;

        [ModelField("item")]
        public byte item;

        [ModelField("xp")]
        public byte xp;

        [ModelField("level")]
        public byte level;

        [ModelField("health")]
        public byte health;

        [ModelField("attack")]
        public byte attack;

        [ModelField("absorb")]
        public byte absorb;

        [ModelField("stun")]
        public byte stun;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        