// Generated by dojo-bindgen on Wed, 14 Aug 2024 21:35:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace zklash {
    // Model definition for `zklash::models::index::Registry` model
    public class Registry : ModelInstance {
        [ModelField("id")]
        public uint id;

        [ModelField("squad_count")]
        public uint squad_count;

        [ModelField("leagues")]
        public FieldElement leagues;

        [ModelField("seed")]
        public FieldElement seed;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        