// Generated by dojo-bindgen on Wed, 14 Aug 2024 21:35:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using Dojo.Torii;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace zklash
{
    // Model definition for `zklash::models::index::Player` model
    public class Player : ModelInstance
    {
        [ModelField("id")]
        public FieldElement id;

        [ModelField("name")]
        public FieldElement name;

        [ModelField("team_count")]
        public uint team_count;

        [ModelField("win_count")]
        public uint win_count;

        // Start is called before the first frame update
        void Start()
        {
        }

        // Update is called once per frame
        void Update()
        {
        }

        public override void OnUpdate(Model model)
        {
            //Debug.Log($"Team updated: {model}");
            base.OnUpdate(model);
        }
    }
}

