// Generated by dojo-bindgen on Wed, 14 Aug 2024 21:35:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace zklash {
    // Model definition for `zklash::models::index::Squad` model
    public class Squad : ModelInstance {
        [ModelField("registry_id")]
        public uint registry_id;

        [ModelField("id")]
        public uint id;

        [ModelField("league_id")]
        public byte league_id;

        [ModelField("index")]
        public uint index;

        [ModelField("rating")]
        public uint rating;

        [ModelField("size")]
        public byte size;

        [ModelField("name")]
        public FieldElement name;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        