// Generated by dojo-bindgen on Wed, 14 Aug 2024 21:35:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using Dojo.Torii;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using UnityEngine;


namespace zklash
{
    // Model definition for `zklash::models::index::Team` model
    public class Team : ModelInstance
    {
        [ModelField("player_id")]
        public FieldElement player_id;

        [ModelField("id")]
        public uint id;

        [ModelField("registry_id")]
        public uint registry_id;

        [ModelField("gold")]
        public uint gold;

        [ModelField("health")]
        public uint health;

        [ModelField("level")]
        public byte level;

        [ModelField("character_uuid")]
        public byte character_uuid;

        [ModelField("battle_id")]
        public byte battle_id;

        [ModelField("foe_squad_id")]
        public uint foe_squad_id;

        // Start is called before the first frame update
        void Start()
        {
        }

        // Update is called once per frame
        void Update()
        {
        }

        public override void OnUpdate(Model model)
        {
            Debug.Log($"Team updated: {model}");
            base.OnUpdate(model);
        }
    }
}

