kind = "DojoContract"
class_hash = "0x74251f03d9767de8858df9483c80c0fe24751765ae6a9eecfdecec615e9d585"
original_class_hash = "0x74251f03d9767de8858df9483c80c0fe24751765ae6a9eecfdecec615e9d585"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zklash-market-aadec017.json"
reads = []
writes = []
init_calldata = []
tag = "zklash-market"
manifest_name = "zklash-market-aadec017"
