kind = "DojoContract"
class_hash = "0xc0109c78caad1d6b1207a130bcf6bc7d4d5aea43a18025315d710d8e5baad8"
original_class_hash = "0xc0109c78caad1d6b1207a130bcf6bc7d4d5aea43a18025315d710d8e5baad8"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zklash-account-56d04506.json"
reads = []
writes = []
init_calldata = []
tag = "zklash-account"
manifest_name = "zklash-account-56d04506"
