kind = "DojoContract"
class_hash = "0x7d3baf6e00e5d8e5149541a25411d506c06cba9a6c1cf71c981390e03df98a"
original_class_hash = "0x7d3baf6e00e5d8e5149541a25411d506c06cba9a6c1cf71c981390e03df98a"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zklash-battle-19c01f18.json"
reads = []
writes = []
init_calldata = []
tag = "zklash-battle"
manifest_name = "zklash-battle-19c01f18"
