kind = "DojoContract"
class_hash = "0x4bfc827aca664cf1aef5404ce211db96012387de6bac1fa6d1bc62c7eec0025"
original_class_hash = "0x4bfc827aca664cf1aef5404ce211db96012387de6bac1fa6d1bc62c7eec0025"
base_class_hash = "0x0"
abi = "manifests/slotdev/abis/base/contracts/zklash_systems_account_account.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zklash::systems::account::account"
