// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:03:07 +0000. Do not modify this file manually.
using UnityEngine;
using System;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;

// Model definition for `zklash::models::character::Character` model
public class Character : ModelInstance {
    [ModelField("player_id")]
    public FieldElement player_id;

    [ModelField("team_id")]
    public uint team_id;

    [ModelField("id")]
    public byte id;

    [ModelField("role")]
    public byte role;

    [ModelField("item")]
    public byte item;

    [ModelField("xp")]
    public byte xp;

    [ModelField("level")]
    public byte level;

    [ModelField("health")]
    public byte health;

    [ModelField("attack")]
    public byte attack;

    [ModelField("absorb")]
    public byte absorb;

    [ModelField("stun")]
    public bool stun;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
    
    public override void OnUpdate(Model model)
    {
        Debug.Log($"Player updated: {model}");
        base.OnUpdate(model);
    }
}
        