// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:03:07 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `zklash::models::character::Character` model
public class Character : ModelInstance {
    [ModelField("player_id")]
    public FieldElement player_id;

    [ModelField("team_id")]
    public uint team_id;

    [ModelField("id")]
    public ushort id;

    [ModelField("role")]
    public byte role;

    [ModelField("xp")]
    public uint xp;

    [ModelField("level")]
    public byte level;

    [ModelField("health")]
    public byte health;

    [ModelField("attack")]
    public byte attack;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        