// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:03:07 +0000. Do not modify this file manually.
using UnityEngine;
using System;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;
using System.Numerics;


// Model definition for `zklash::models::shop::Shop` model
public class Shop : ModelInstance {
    [ModelField("player_id")]
    public FieldElement player_id;

    [ModelField("team_id")]
    public uint team_id;

    [ModelField("purchase_cost")]
    public byte purchase_cost;

    [ModelField("reroll_cost")]
    public byte reroll_cost;

    [ModelField("item_count")]
    public byte item_count;

    [ModelField("items")]
    public uint items;

    [ModelField("role_count")]
    public byte role_count;

    [ModelField("roles")]
    public uint roles;

    // Start is called before the first frame update
    void Start() {
        Debug.Log($"Shop started -> player_id: {player_id}");
    }

    // Update is called once per frame
    void Update() {
    }

    public override void OnUpdate(Model model)
    {
        Debug.Log($"Shop updated: {model}");
        base.OnUpdate(model);
    }
}
        