// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:03:07 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Numerics;


// Model definition for `zklash::models::shop::Shop` model
public class Shop : ModelInstance {
    [ModelField("player_id")]
    public FieldElement player_id;

    [ModelField("team_id")]
    public uint team_id;

    [ModelField("cost")]
    public byte cost;

    [ModelField("roles")]
    public BigInteger roles;

    [ModelField("items")]
    public BigInteger items;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        