// Generated by dojo-bindgen on Fri, 5 Apr 2024 08:03:07 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `zklash::models::team::Team` model
public class Team : ModelInstance {
    [ModelField("player_id")]
    public FieldElement player_id;

    [ModelField("id")]
    public uint id;

    [ModelField("seed")]
    public FieldElement seed;

    [ModelField("gold")]
    public uint gold;

    [ModelField("health")]
    public uint health;

    [ModelField("level")]
    public byte level;

    [ModelField("characters")]
    public ulong characters;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        