kind = "DojoModel"
class_hash = "0x12a9a81e5453e31963158c4c9fe463e90868c74a3103b31a4149d0498e2af8f"
original_class_hash = "0x12a9a81e5453e31963158c4c9fe463e90868c74a3103b31a4149d0498e2af8f"
abi = "manifests/dev/abis/base/models/zklash_models_foe_foe.json"
name = "zklash::models::foe::foe"

[[members]]
name = "registry_id"
type = "u32"
key = true

[[members]]
name = "squad_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "role"
type = "u8"
key = false

[[members]]
name = "item"
type = "u8"
key = false

[[members]]
name = "level"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "attack"
type = "u8"
key = false

[[members]]
name = "absorb"
type = "u8"
key = false

[[members]]
name = "stun"
type = "u8"
key = false
