kind = "DojoModel"
class_hash = "0xf814988ad08adabe563a801f4d127cc9f426d64ec3181b42fe3e965a17055e"
original_class_hash = "0xf814988ad08adabe563a801f4d127cc9f426d64ec3181b42fe3e965a17055e"
abi = "manifests/dev/abis/base/models/zklash_models_index_shop.json"
name = "zklash::models::index::shop"

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "team_id"
type = "u32"
key = true

[[members]]
name = "reroll_cost"
type = "u8"
key = false

[[members]]
name = "item_count"
type = "u8"
key = false

[[members]]
name = "items"
type = "u32"
key = false

[[members]]
name = "role_count"
type = "u8"
key = false

[[members]]
name = "roles"
type = "u32"
key = false
