kind = "DojoModel"
class_hash = "0x76b46b423917e802e249949142e58415eec85c21b1c5ddf9907e7f91b71397c"
original_class_hash = "0x76b46b423917e802e249949142e58415eec85c21b1c5ddf9907e7f91b71397c"
abi = "manifests/dev/abis/base/models/zklash_models_slot_slot.json"
name = "zklash::models::slot::slot"

[[members]]
name = "registry_id"
type = "u32"
key = true

[[members]]
name = "league_id"
type = "u8"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "squad_id"
type = "u32"
key = false
