kind = "DojoModel"
class_hash = "0x3017b0b96d27e089ef1cea77e21603dc2f7f01c86d0ec98f44b0908beb1dff0"
original_class_hash = "0x3017b0b96d27e089ef1cea77e21603dc2f7f01c86d0ec98f44b0908beb1dff0"
abi = "manifests/dev/abis/base/models/zklash_models_league_league.json"
name = "zklash::models::league::league"

[[members]]
name = "registry_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "size"
type = "u32"
key = false
