kind = "DojoModel"
class_hash = "0x29893b200d52febfc1b9c30383480bc8b10dca4a9ec22bbdfba63e577ef8a3f"
original_class_hash = "0x29893b200d52febfc1b9c30383480bc8b10dca4a9ec22bbdfba63e577ef8a3f"
abi = "manifests/dev/abis/base/models/zklash_models_index_character.json"
name = "zklash::models::index::character"

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "team_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "role"
type = "u8"
key = false

[[members]]
name = "item"
type = "u8"
key = false

[[members]]
name = "xp"
type = "u8"
key = false

[[members]]
name = "level"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "attack"
type = "u8"
key = false

[[members]]
name = "absorb"
type = "u8"
key = false

[[members]]
name = "stun"
type = "u8"
key = false
