kind = "DojoModel"
class_hash = "0x1199d583ea7eb7689fd272895963cb97896a4c2471c4b12a18fbb582de305bb"
original_class_hash = "0x1199d583ea7eb7689fd272895963cb97896a4c2471c4b12a18fbb582de305bb"
abi = "manifests/dev/abis/base/models/zklash_models_index_squad.json"
name = "zklash::models::index::squad"

[[members]]
name = "registry_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "league_id"
type = "u8"
key = false

[[members]]
name = "index"
type = "u32"
key = false

[[members]]
name = "rating"
type = "u32"
key = false

[[members]]
name = "size"
type = "u8"
key = false

[[members]]
name = "name"
type = "felt252"
key = false
