kind = "DojoModel"
class_hash = "0x783c36f4689aa3063ce9cd188291edc2a5ca120b495ad88c2926407b42dd4a5"
original_class_hash = "0x783c36f4689aa3063ce9cd188291edc2a5ca120b495ad88c2926407b42dd4a5"
abi = "manifests/dev/abis/base/models/zklash_models_character_character.json"
name = "zklash::models::character::character"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "team_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "role"
type = "u8"
key = false

[[members]]
name = "item"
type = "u8"
key = false

[[members]]
name = "xp"
type = "u8"
key = false

[[members]]
name = "level"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "attack"
type = "u8"
key = false

[[members]]
name = "absorb"
type = "u8"
key = false

[[members]]
name = "stun"
type = "u8"
key = false
