kind = "DojoModel"
class_hash = "0x37c35d440d3fdb1389684a2ac05ba9ff13879521b515836194d5558ffc9e8c3"
original_class_hash = "0x37c35d440d3fdb1389684a2ac05ba9ff13879521b515836194d5558ffc9e8c3"
abi = "manifests/dev/abis/base/models/zklash_models_index_shop.json"
name = "zklash::models::index::shop"

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "team_id"
type = "u32"
key = true

[[members]]
name = "purchase_cost"
type = "u8"
key = false

[[members]]
name = "reroll_cost"
type = "u8"
key = false

[[members]]
name = "item_count"
type = "u8"
key = false

[[members]]
name = "items"
type = "u32"
key = false

[[members]]
name = "role_count"
type = "u8"
key = false

[[members]]
name = "roles"
type = "u32"
key = false
