kind = "DojoModel"
class_hash = "0x28b3d16a5d67d1f41c5d99eacd780309ac6909da04e5989632c5e8fccea7608"
original_class_hash = "0x28b3d16a5d67d1f41c5d99eacd780309ac6909da04e5989632c5e8fccea7608"
abi = "manifests/dev/abis/base/models/zklash_models_registry_registry.json"
name = "zklash::models::registry::registry"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "squad_count"
type = "u32"
key = false

[[members]]
name = "leagues"
type = "felt252"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false
