kind = "DojoModel"
class_hash = "0x239eb51ece58e989c5aa738e76c3bc01ebdc5ab1162a63a6aa5b7dbb78ab560"
original_class_hash = "0x239eb51ece58e989c5aa738e76c3bc01ebdc5ab1162a63a6aa5b7dbb78ab560"
abi = "manifests/dev/abis/base/models/zklash_models_registry_registry.json"
name = "zklash::models::registry::registry"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "squad_count"
type = "u32"
key = false

[[members]]
name = "leagues"
type = "felt252"
key = false
