kind = "DojoModel"
class_hash = "0x6ace9a5de5e7da268c719990ddb72809962723be23a0746361d87c409fd6327"
original_class_hash = "0x6ace9a5de5e7da268c719990ddb72809962723be23a0746361d87c409fd6327"
abi = "manifests/dev/abis/base/models/zklash_models_character_character.json"
name = "zklash::models::character::character"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "team_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "role"
type = "u8"
key = false

[[members]]
name = "item"
type = "u8"
key = false

[[members]]
name = "xp"
type = "u32"
key = false

[[members]]
name = "level"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "attack"
type = "u8"
key = false
