kind = "DojoModel"
class_hash = "0x7e6bf1e60f46c9ee8b0de2acc5d4a536bfe3c936eeb644b333ad0304d0c7814"
original_class_hash = "0x7e6bf1e60f46c9ee8b0de2acc5d4a536bfe3c936eeb644b333ad0304d0c7814"
abi = "manifests/dev/abis/base/models/zklash_models_team_team.json"
name = "zklash::models::team::team"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "gold"
type = "u32"
key = false

[[members]]
name = "health"
type = "u32"
key = false

[[members]]
name = "level"
type = "u8"
key = false

[[members]]
name = "characters"
type = "u64"
key = false
