kind = "DojoModel"
class_hash = "0x57496d7e8d5ef077c221db4e64dd6e8e280959f6b937953f4feb1daf2b3cae8"
original_class_hash = "0x57496d7e8d5ef077c221db4e64dd6e8e280959f6b937953f4feb1daf2b3cae8"
abi = "manifests/dev/abis/base/models/zklash_models_index_foe.json"
name = "zklash::models::index::foe"

[[members]]
name = "registry_id"
type = "u32"
key = true

[[members]]
name = "squad_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "role"
type = "u8"
key = false

[[members]]
name = "item"
type = "u8"
key = false

[[members]]
name = "level"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "attack"
type = "u8"
key = false

[[members]]
name = "absorb"
type = "u8"
key = false

[[members]]
name = "stun"
type = "u8"
key = false
