// Generated by dojo-bindgen on Fri, 5 Apr 2024 16:22:12 +0000. Do not modify this file manually.
using System;
using System.Threading.Tasks;
using Dojo;
using Dojo.Starknet;
using UnityEngine;
using dojo_bindings;
using System.Numerics;

// System definitions for `zklash::systems::battle::battle` contract
public class BattleSystem : MonoBehaviour {
    // The address of this contract
    public string contractAddress;

    
    // Call the `dojo_resource` system with the specified Account and calldata
    // Returns the transaction hash. Use `WaitForTransaction` to wait for the transaction to be confirmed.
    public async Task<FieldElement> DojoResource(Account account) {
        return await account.ExecuteRaw(new dojo.Call[] {
            new dojo.Call{
                to = contractAddress,
                selector = "dojo_resource",
                calldata = new dojo.FieldElement[] {
                    
                }
            }
        });
    }
            

    
    // Call the `start` system with the specified Account and calldata
    // Returns the transaction hash. Use `WaitForTransaction` to wait for the transaction to be confirmed.
    public async Task<FieldElement> StartBattle(Account account, string world, uint team_id, uint order) {
        return await account.ExecuteRaw(new dojo.Call[] {
            new dojo.Call{
                to = contractAddress,
                selector = "start",
                calldata = new dojo.FieldElement[] {
                    new FieldElement(world).Inner,
                    new FieldElement(team_id).Inner,
                    new FieldElement(order).Inner
                }
            }
        });
    }
            
}
        