tag = "zklash-account"
writes = [
    "zklash-Character",
    "zklash-Foe",
    "zklash-League",
    "zklash-Player",
    "zklash-Registry",
    "zklash-Shop",
    "zklash-Slot",
    "zklash-Squad",
    "zklash-Team",
]
