[package]
cairo-version = "2.5.4"
name = "zklash"
version = "0.6.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo --profile dev build && sozo --profile dev migrate plan && sozo --profile dev migrate apply && ./scripts/authorize.sh dev"
slot = "sozo --profile slot build && sozo --profile slot migrate plan --name v0 && sozo --profile slot migrate apply --name v0 && ./scripts/authorize.sh slot"

[dependencies]
origami = { git = "https://github.com/dojoengine/origami", rev = "501dcd4" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[profile.dev.tool.dojo.env]
rpc_url = "http://localhost:5050"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"

[profile.slot.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/zklash-matthias-3/katana" 
#"https://api.cartridge.gg/x/zklash/katana/"
account_address = "0x7fb5fb8033b9f199ba9347c2f8c1bdbbd47d8a22c09d25b5a29c183ddb47252"
private_key = "0x76165bfb2708ab726999aa73d95d9a0bbaa94f9ced060dc5393ecdd020f9079"

[profile.sepolia.tool.dojo.env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_6"
account_address = "0x063fd4be5b4df3068e3c4ae4062e999609b96a569e69628d6ba3331bf56e826c"
private_key = "0x05c38e8a5fe551d71755d7c4c77ea8aa7083479b222b413fef3772205fefec00"

[tool.dojo.world]
name = "zKlash"
description = "Autobattler where you hire creatures and improve them to defeat waves of enemies."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"

[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
