kind = "DojoContract"
class_hash = "0x471a6c61ad82a916976bae86c3a7ebdaf920845a5610224b2e36d846bbf09ac"
original_class_hash = "0x471a6c61ad82a916976bae86c3a7ebdaf920845a5610224b2e36d846bbf09ac"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/zklash_systems_account_account.json"
reads = []
writes = []
computed = []
name = "zklash::systems::account::account"
