kind = "DojoContract"
class_hash = "0x2b3d0d5315c354b84bfd790f169f8e5c8d9ee673c58486322865341d3205ae5"
original_class_hash = "0x2b3d0d5315c354b84bfd790f169f8e5c8d9ee673c58486322865341d3205ae5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_market_market.json"
reads = []
writes = []
computed = []
name = "zklash::systems::market::market"
