kind = "DojoContract"
class_hash = "0x5c733e2fce08d7b489dcee30a93da07e2e2c7af085ec5b6eeac2e76e3191912"
original_class_hash = "0x5c733e2fce08d7b489dcee30a93da07e2e2c7af085ec5b6eeac2e76e3191912"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
