kind = "DojoContract"
class_hash = "0x2b1d1936f30bb270a0bb36aed29f33f9cb16f3aed138a878d646f40f2a65e6d"
original_class_hash = "0x2b1d1936f30bb270a0bb36aed29f33f9cb16f3aed138a878d646f40f2a65e6d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_account_account.json"
reads = []
writes = []
computed = []
name = "zklash::systems::account::account"
