kind = "DojoContract"
class_hash = "0x7e6c239f6fffe65bf9a0c8ae1c128e1267e5673be9ed4da9a8579a605d51b49"
original_class_hash = "0x7e6c239f6fffe65bf9a0c8ae1c128e1267e5673be9ed4da9a8579a605d51b49"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
