kind = "DojoContract"
class_hash = "0x6bd21b6f3870b2a8b77c97db5a26822cc98ddda79b98e3051e14922f361f9a5"
original_class_hash = "0x6bd21b6f3870b2a8b77c97db5a26822cc98ddda79b98e3051e14922f361f9a5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_account_account.json"
reads = []
writes = []
computed = []
name = "zklash::systems::account::account"
