kind = "DojoContract"
class_hash = "0x2510262aac14634a80a2b2849a976a974e2794bafccabacda6ed8ed76664a78"
original_class_hash = "0x2510262aac14634a80a2b2849a976a974e2794bafccabacda6ed8ed76664a78"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
