kind = "DojoContract"
class_hash = "0x76c82c0df1c36d039d9e69505603d1ac848825cce8bc11032b4fe8e0ac79acf"
original_class_hash = "0x76c82c0df1c36d039d9e69505603d1ac848825cce8bc11032b4fe8e0ac79acf"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
