kind = "DojoContract"
class_hash = "0x2f88eb9fd59e029963bbd7d2a2c63be4f44a53716f20dbd69217898377a20ae"
original_class_hash = "0x2f88eb9fd59e029963bbd7d2a2c63be4f44a53716f20dbd69217898377a20ae"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_account_account.json"
reads = []
writes = []
computed = []
name = "zklash::systems::account::account"
