kind = "DojoContract"
class_hash = "0x3d5f33a122beb421356184704b5218b16c4f24e9ffb252d51676c442e24cf14"
original_class_hash = "0x3d5f33a122beb421356184704b5218b16c4f24e9ffb252d51676c442e24cf14"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zklash::systems::battle::battle"
