kind = "DojoContract"
class_hash = "0x5b0be4de62b42812a7f78a3b01d4a11b23c568ab4e6f73ecc446be6d19da44c"
original_class_hash = "0x5b0be4de62b42812a7f78a3b01d4a11b23c568ab4e6f73ecc446be6d19da44c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
