kind = "DojoContract"
class_hash = "0x457d48cf16322caba596bc05f7370093d29f63a0c07312fbf4ec20d1e62e654"
original_class_hash = "0x457d48cf16322caba596bc05f7370093d29f63a0c07312fbf4ec20d1e62e654"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_market_market.json"
reads = []
writes = []
computed = []
name = "zklash::systems::market::market"
