kind = "DojoContract"
class_hash = "0x5b2b9bdc48b703f5e625aac8987e1a962b0409e52d08d4f4b95689cfd989757"
original_class_hash = "0x5b2b9bdc48b703f5e625aac8987e1a962b0409e52d08d4f4b95689cfd989757"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
