kind = "DojoContract"
class_hash = "0x10b78be9c123150662e56e3a0028c2d3da278fd312ef79a903356ec301ba041"
original_class_hash = "0x10b78be9c123150662e56e3a0028c2d3da278fd312ef79a903356ec301ba041"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_account_account.json"
reads = []
writes = []
computed = []
name = "zklash::systems::account::account"
