kind = "DojoContract"
class_hash = "0x28fd56aa160462b6fb5c396241376a20fcfabb3033d7c636d8a8beac6bc840"
original_class_hash = "0x28fd56aa160462b6fb5c396241376a20fcfabb3033d7c636d8a8beac6bc840"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zklash-battle-19c01f18.json"
reads = []
writes = []
init_calldata = []
tag = "zklash-battle"
manifest_name = "zklash-battle-19c01f18"
