kind = "DojoContract"
class_hash = "0x8ee6dc805536af41ca1a1c7734c47ff596c1068f39763f8f540a9ab0041340"
original_class_hash = "0x8ee6dc805536af41ca1a1c7734c47ff596c1068f39763f8f540a9ab0041340"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
