kind = "DojoContract"
class_hash = "0x5c4ccdbe148bdf12ca152aa1c8eda12c0d50659e7b15b7156c097a05a43a3c8"
original_class_hash = "0x5c4ccdbe148bdf12ca152aa1c8eda12c0d50659e7b15b7156c097a05a43a3c8"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
