kind = "DojoContract"
class_hash = "0x21137e8805d511c37c4f717d9f13a2c926cd9d25addcc9e6c0455e34773098e"
original_class_hash = "0x21137e8805d511c37c4f717d9f13a2c926cd9d25addcc9e6c0455e34773098e"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
