kind = "DojoContract"
class_hash = "0x6a74247c055d52650e24f62f8df54076016540ba1cea0f68e024a420087614d"
original_class_hash = "0x6a74247c055d52650e24f62f8df54076016540ba1cea0f68e024a420087614d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_market_market.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zklash::systems::market::market"
