kind = "DojoContract"
class_hash = "0x3da274a3b9db1eb9f949c9dd70b0315706b7abb550ca8615ed0d974063b7cbe"
original_class_hash = "0x3da274a3b9db1eb9f949c9dd70b0315706b7abb550ca8615ed0d974063b7cbe"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
