kind = "DojoContract"
class_hash = "0x642aaa6811ce42b61fed75d5fabee1d070a10a04c01920fcfe7f8f19e4ea8a5"
original_class_hash = "0x642aaa6811ce42b61fed75d5fabee1d070a10a04c01920fcfe7f8f19e4ea8a5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_market_market.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zklash::systems::market::market"
