kind = "DojoContract"
class_hash = "0x3cc481d3bf4bdf9db4f9f2370ed37f99f2eddfac267e856ecc868a1635e08f"
original_class_hash = "0x3cc481d3bf4bdf9db4f9f2370ed37f99f2eddfac267e856ecc868a1635e08f"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zklash_systems_battle_battle.json"
reads = []
writes = []
computed = []
name = "zklash::systems::battle::battle"
