kind = "DojoContract"
class_hash = "0x53d22fe9a88a6868c72330a65d3ff3115edd1ca67d03ed345116ea7230f4096"
original_class_hash = "0x53d22fe9a88a6868c72330a65d3ff3115edd1ca67d03ed345116ea7230f4096"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zklash-market-aadec017.json"
reads = []
writes = []
init_calldata = []
tag = "zklash-market"
manifest_name = "zklash-market-aadec017"
